"""empty message

Revision ID: 2f42460d9060
Revises: be632a33e4bf
Create Date: 2017-01-28 22:28:36.332858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f42460d9060'
down_revision = 'be632a33e4bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('membership')
    op.drop_constraint('group_name_key', 'group', type_='unique')
    op.drop_column('group', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group', sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.create_unique_constraint('group_name_key', 'group', ['name'])
    op.create_table('membership',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], name='membership_group_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='membership_user_id_fkey'),
    sa.PrimaryKeyConstraint('user_id', 'group_id', name='membership_pkey')
    )
    # ### end Alembic commands ###
