"""empty message

Revision ID: 30b694d51431
Revises: 7e179bd03a33
Create Date: 2017-01-28 17:01:01.178793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30b694d51431'
down_revision = '7e179bd03a33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('share', sa.Column('device_id', sa.Integer(), nullable=True))
    op.add_column('share', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_unique_constraint('shares_name_user_id_uc', 'share', ['name', 'user_id'])
    op.create_foreign_key(None, 'share', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'share', 'device', ['device_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'share', type_='foreignkey')
    op.drop_constraint(None, 'share', type_='foreignkey')
    op.drop_constraint('shares_name_user_id_uc', 'share', type_='unique')
    op.drop_column('share', 'user_id')
    op.drop_column('share', 'device_id')
    # ### end Alembic commands ###
