"""empty message

Revision ID: 8c3217e33581
Revises: 4b1228d07c61
Create Date: 2017-01-29 10:00:04.920831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c3217e33581'
down_revision = '4b1228d07c61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('path_share_id_fkey', 'path', type_='foreignkey')
    op.create_foreign_key(None, 'path', 'share', ['share_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('share_device_id_fkey', 'share', type_='foreignkey')
    op.create_foreign_key(None, 'share', 'device', ['device_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'share', type_='foreignkey')
    op.create_foreign_key('share_device_id_fkey', 'share', 'device', ['device_id'], ['id'])
    op.drop_constraint(None, 'path', type_='foreignkey')
    op.create_foreign_key('path_share_id_fkey', 'path', 'share', ['share_id'], ['id'])
    # ### end Alembic commands ###
