"""empty message

Revision ID: 93455be47e90
Revises: cc60c34245c1
Create Date: 2017-01-28 23:08:48.139769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93455be47e90'
down_revision = 'cc60c34245c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_group_association',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.UniqueConstraint('user_id', 'group_id', name='user_group_association_uc')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_group_association')
    # ### end Alembic commands ###
