"""empty message

Revision ID: dc58655fd036
Revises: 8c3217e33581
Create Date: 2017-01-29 23:40:36.990855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc58655fd036'
down_revision = '8c3217e33581'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('share_group_association',
    sa.Column('share_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['share_id'], ['share.id'], ),
    sa.UniqueConstraint('share_id', 'group_id', name='share_group_association_uc')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('share_group_association')
    # ### end Alembic commands ###
